### ISSUE TITLE
'fr24feed.service' config file does not stop logging to /var/log/fr24feed/fr24feed.log 

### ISSUE THREAD

**Issue by DarS007** [wiedehopf/adsb-scripts#1]
Thanks for the scripts! 
I've just installed `fr24feed.service` config file from GitHub, restarted both:
 - systemctl daemon
 - fr24feed service

and noticed that `fr24feed` **still** keeps logging to `/var/log/fr24feed/fr24feed.log` on my Raspberry Pi 3. 
Actually, the `fr24feed.service` config enabled **both** log destinations:
 - occasional (every 10 minutes?) syslog logs with proper `fr24feed` SyslogIdentifier 
 - frequent (as usual) logs to `/var/log/fr24feed/fr24feed.log` file.

When I stopped fr24feed service a minute ago, the `/var/log/fr24feed/fr24feed.log` file reflected this:

`[main][i]Terminating on user request`
`[main][i]Terminating worker threads`

How can I troubleshoot this issue further?  I would like to turn OFF the `/var/log/fr24feed/fr24feed.log` to protect SD card.

Regards,
-DarS

**Comment by wiedehopf** [comment]
logging to that file is determined by fr24feed.ini
