### ISSUE TITLE
Update failed (Initialization of state variables in list context currently forbidden)

### ISSUE THREAD

**Issue by giddyhup** [wiedehopf/adsb-scripts#14]
I wanted to update readsb via the update/install script and the following error happened:

```
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build git
 debian/rules clean
dh clean --with=systemd
Initialization of state variables in list context currently forbidden at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 2032, near ");"
BEGIN not safe after errors--compilation aborted at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 2716.
Compilation failed in require at /usr/bin/dh line 15.
BEGIN failed--compilation aborted at /usr/bin/dh line 15.
debian/rules:54: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: debian/rules clean gave error exit status 2
Something went wrong building the debian package, exiting!

```

This is under buster Raspberry OS.

**Comment by giddyhup** [comment]
Should I update perl?

```
 perl -v

This is perl 5, version 24, subversion 1 (v5.24.1) built for arm-linux-gnueabihf-thread-multi-64int
(with 86 registered patches, see perl -V for more detail)

```

**Comment by wiedehopf** [comment]
Just update the pi?
```
sudo apt update && sudo apt dist-upgrade
```

Can't reproduce the error.

**Comment by giddyhup** [comment]
Thanks for the quick feedback. You were right, the pi was in dire need of an update. A simple update/upgrade wasn't enough, a dist-upgrade was needed. Writing the web server conf file failed but since this was an upgrade and not a fresh install it didn't matter. I restarted the service and everything looks good.

(The conf file cp error:
```
Processing triggers for man-db (2.8.5-2) ...
Package installed!
cp: cannot stat 'debian/lighttpd/*': No such file or directory
[ERROR] Error in line 82 when executing: cp -n debian/lighttpd/* /etc/lighttpd/conf-available
```
)

**Comment by wiedehopf** [comment]
Sorry that was me messing with my readsb repository.
Should have fixed it rather quickly though.

**Comment by wiedehopf** [comment]
So feel free to rerun, it should all work now.

**Comment by giddyhup** [comment]
Thanks for the explanation. If I am not mistaken, none of the steps following the failure are needed in my situation so I guess I'll leave it the way it is.

**Comment by wiedehopf** [comment]
Did it update tar1090 as well? And restart readsb?
You can always do that manually i suppose.

**Comment by giddyhup** [comment]
I actually updated tar1090 on its own before readsb and also restarted the service manually.

**Comment by wiedehopf** [comment]
Btw i just fixed the graphs1090 install script ... should really test that stuff :)
https://github.com/wiedehopf/graphs1090#graphs1090

**Comment by giddyhup** [comment]
Ok, ok. I messed with my gain settings and used the occasion while fixing it to run the full install/update script. Everything worked nicely.

**Comment by giddyhup** [comment]
The range diagram is new to me, neat.
