### ISSUE TITLE
awk syntax error

### ISSUE THREAD

**Issue by upD8R** [wiedehopf/adsb-scripts#17]
Hi there,

just setting up a new RPi with your very cool scripts but after installing autogain1090 I get an awk syntax error (the "basic" stuff works as expected as far as I can tell):
```
pi@flight:~ $ sudo autogain1090
awk: line 1: syntax error at or near }
awk: line 1: syntax error at or near }
No gain change needed, percentage of messages >-3dB is in nominal range. (0,968%)
```
Any idea?

**Comment by wiedehopf** [comment]
does it persist or was it only happening on first run?

**Comment by wiedehopf** [comment]
Run the install again, see if the error is gone.

**Comment by upD8R** [comment]
It persists, also after 2nd installation.

Looks like a variable is not (yet) populated? But I don't know, which awk is throwing this error.

**Comment by wiedehopf** [comment]
Edit /usr/local/bin/autogain1090 and add a set -x at the start of the script.

**Comment by upD8R** [comment]
Something "," vs "."?
```
+ awk 'BEGIN{ exit (0,000 > 0.5) }'
awk: line 1: syntax error at or near }
+ awk 'BEGIN{ exit (0,000 < 7.0) }'
awk: line 1: syntax error at or near }

```

**Comment by wiedehopf** [comment]
Yeah it's your locale .... i really don't know why awk depends on locale it's very annoying.

Ok ... try another install, should  be fixed.

**Comment by upD8R** [comment]
Many thanks, by Googling I was also ending up at my locale ;-)

It is fixed now, thanks indeed for your outstanding support!
