### ISSUE TITLE
Use of mictronics readsb instead of your own

### ISSUE THREAD

**Issue by MansM** [wiedehopf/adsb-scripts#2]
In a couple of your script I have noticed you use the mictronics version of readsb instead of your own. Wouldn’t it be more useful to change that?

**Comment by wiedehopf** [comment]
My fork is mostly for server use and some more experimental features.
If people don't compile themselves, no reason to invite that sort of complication at the moment.
My repo also doesn't have the integral webinterface which some people expect.
