### ISSUE TITLE
Version bump for fr24feed to 1.0.46-2

### ISSUE THREAD

**Issue by tiffchros** [wiedehopf/adsb-scripts#38]
After fresh install of my ADS-B feeder, I was wondering why it had an older version shown on the web-interface than my other one installed several years ago.

Workaround:

- Download https://raw.githubusercontent.com/wiedehopf/adsb-scripts/master/fr24-nopackage.sh manually
- Exchanged line 24
  - `- wget -O fr24.deb https://repo-feed.flightradar24.com/rpi_binaries/fr24feed_1.0.34-0_armhf.deb`
  - `+ wget -O fr24.deb https://repo-feed.flightradar24.com/rpi_binaries/fr24feed_1.0.46-2_armhf.deb`
- Executing

And everything worked like a charm on my raspberry pis.

**Comment by wiedehopf** [comment]
Their software is often buggy so i don't update the version unless necessary.
But doesn't hurt to update now.
