### ISSUE TITLE
Problem with pi4 adsb-script

### ISSUE THREAD

**Issue by lordkane** [wiedehopf/adsb-scripts#4]
hi i have a problem with install readsb-install.sh
i have a error
dpkg-checkbuilddeps: Fehler: Nicht erfüllte Bauabhängigkeiten: librtlsdr-dev

**Comment by wiedehopf** [comment]
Install the package manually, see if that works.

```
apt-get update
apt-get install --no-install-recommends --no-install-suggests -y git build-essential debhelper libusb-1.0-0-dev \
    librtlsdr-dev librtlsdr0 pkg-config dh-systemd \
    libncurses5-dev lighttpd zlib1g-dev zlib1g
```

**Comment by lordkane** [comment]
Does not workGesendet mit der GMX Mail AppAm 10.10.20 um 19:38 schrieb wiedehopf
                
            
            
                
                    Von: "wiedehopf" <notifications@github.com>Datum: 10. Oktober 2020An: "wiedehopf/adsb-scripts" <adsb-scripts@noreply.github.com>Cc: "Author" <author@noreply.github.com>,"lordkane" <bonzai24@gmx.de>Betreff: Re: [wiedehopf/adsb-scripts] Problem with pi4 adsb-script (#4)
                
                
Install the package manually, see if that works.
apt-get update
apt-get install --no-install-recommends --no-install-suggests -y git build-essential debhelper libusb-1.0-0-dev \
    librtlsdr-dev librtlsdr0 pkg-config dh-systemd \
    libncurses5-dev lighttpd zlib1g-dev zlib1g


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wiedehopf/adsb-scripts/issues/4#issuecomment-706585633",
"url": "https://github.com/wiedehopf/adsb-scripts/issues/4#issuecomment-706585633",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lordkane** [comment]
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 librtlsdr-dev : Hängt ab von: librtlsdr0 (= 0.6-1+rpt1) aber 0.6git soll installiert werden
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by wiedehopf** [comment]
you'll have to remove the blocking packet.

sudo apt remove librtlsdr0

then try again to install.
