### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by gHashFlyer** [wiedehopf/adsb-scripts#43]
Discord invite is invalid.

**Comment by wiedehopf** [comment]
Which? Where?

**Comment by gHashFlyer** [comment]
Oh sorry - it was here:  https://github.com/wiedehopf/adsb-wiki/wiki/Raspbian-Lite%3A-ADS-B-receiver

**Comment by wiedehopf** [comment]
works for me.

**Comment by wiedehopf** [comment]
https://discord.gg/DxU4VG37JS

This one or the other one ... they both work for me.
So you'll have to be more specific.

**Comment by gHashFlyer** [comment]
[image: 2024-10-10_182057.jpg]

**Comment by wiedehopf** [comment]
no picture from email it seems.

**Comment by gHashFlyer** [comment]
https://ibb.co/P6yrtvB

**Comment by wiedehopf** [comment]
Either you're one of the 2 banned accounts or it's a discord issue.
