### ISSUE TITLE
404 error on the readsb install script

### ISSUE THREAD

**Issue by jimpfaff** [wiedehopf/adsb-scripts#44]
I'm attempting to run the script to add the reader with

```
sudo bash -c "$(wget -O - https://github.com/weidehopf/adsb-scripts/raw/master/readsb-install.sh)"
```

But I'm receiving a 404 error. Has the script moved? If so, it's not updated in the instructions.

**Comment by wiedehopf** [comment]
You got a typo in there, where is that from?

**Comment by jimpfaff** [comment]
https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb

**Comment by jimpfaff** [comment]
Damn!!! haha. You'd think with a last name like mine I would see that after looking over and over. Thanks
