### ISSUE TITLE
Not an issue, but a compliment about automatic gain optimization

### ISSUE THREAD

**Issue by MrBeBo999** [wiedehopf/adsb-scripts#9]
In the evening I had to reboot my pi and saw very bad signals. Next day, I saw this graph. AGO is working superb on 2:45 !!!
![Automatic gain](https://user-images.githubusercontent.com/80465623/115718197-30cd5500-a37b-11eb-807d-1582103d1d16.png)

**Comment by wiedehopf** [comment]
The automatic gain change will only change by one step.
This seems like something else was going on.

**Comment by wiedehopf** [comment]
I suppose restarting readsb / dump1090-fa might have fixed whatever was the issue .... rare but i've seen it before with SDR not working correctly for a time.
Might be an early sign of the SDR failing.
